name: Integration Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - uses: Swatinem/rust-cache@v2
      with:
        cache-on-failure: "true"

    - name: Install dependencies of JS library
      run: npm ci
      working-directory: examples
    - name: Install integration tests
      run: npm ci
      working-directory: tests
    - name: Run integration tests
      run: npm test
      working-directory: tests
