name: Staging Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ] # remove before merging

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: Swatinem/rust-cache@v2
      with:
        cache-on-failure: "true"
        workspaces: y-serve-worker

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 19
    - run: npm ci
      working-directory: ./y-serve-worker
    - run: npm run deploy
      working-directory: ./y-serve-worker
      env:
        CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
